LLM:
  api: 
  key: 
  model: 
GSV:
  text_lang: 
  GPT_weight: 
  SoVITS_weight: 
  ref_audio_path: 
  prompt_text: 
  prompt_lang: 
  aux_ref_audio_paths:
    - 
  seed: -1
  top_k: 15
  batch_size: 1